services:
  - type: web
    name: oyin-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 300 --workers 2 --threads 4 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: oyin_db
      - key: APP_URL
        value: https://ngoainguoyin.vn/
      - key: BREVO_API_KEY
        sync: false
      - key: MAIL_DEFAULT_SENDER
        value: riyue1808@gmail.com
      - key: ADMIN_EMAIL
        sync: false

  - type: cron
    name: keep-alive
    env: python
    schedule: "*/5 * * * *"
    buildCommand: pip install requests
    startCommand: python cron.py
    envVars:
      - key: APP_URL
        value: https://ngoainguoyin.vn/
