services:
  # ===== WEB SERVICE =====
  - type: web
    name: oyin-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    startCommand: gunicorn --timeout 120 --workers 2 --threads 4 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: oyin_db
      - key: APP_URL
        value: https://ngoainguoyin.vn/

  # ===== CRON JOB - GIỮ WEB KHÔNG BỊ SLEEP =====
  - type: cron
    name: keep-alive
    env: python
    schedule: "*/5 * * * *" # Chạy mỗi 5 phút
    buildCommand: pip install requests
    startCommand: python cron.py
    envVars:
      - key: APP_URL
        value: https://ngoainguoyin.vn/
